Workaround to ignore provider/cmd/pulumi-resource-cilium/schema.json change

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -85,8 +85,14 @@ jobs:
       run: |
         git update-index -q --refresh
         if ! git diff-files --quiet; then
-            >&2 echo "error: working tree is not clean, aborting!"
             git status
             git diff
             #exit 1
+        fi
+        git checkout provider/cmd/pulumi-resource-cilium/schema.json
+        if ! git diff-files --quiet; then
+            >&2 echo "error: working tree is not clean, aborting!"
+            git status
+            git diff
+            exit 1
         fi
